import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const defaultEndPoint = 'https://rickandmortyapi.com/api/character'

export async function getServerSideProps(){
  
  const res = await fetch(defaultEndPoint);
  const data = await res.json();

  return{
    props:{
      data
    }
  }
}

export default function Home({data}) {

  //console.log('data:', data )
  const {results = []}  = data;


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rick And Morty
        </h1>

        <div style={{width:'100%', height:'200px', backgroundColor:'#000'}}></div>
        
        <div className={styles.grid}>
          {results.map(result =>{
            const{id, name}=result;
            return(
              <div className={styles.card}>
                <h2>{name}</h2>
              </div>
            )
          }
          )}
          

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
